sensor:
  - name: "Electricity Surplus"
    unique_id: electricity_surplus
    unit_of_measurement: "kW"
    state_class: measurement
    device_class: power
    state: >
      {{ (states('sensor.electricity_meter_power_production') | float(0) 
          - states('sensor.electricity_meter_power_consumption') | float(0)) | round(3) }}
    icon: >
      {% if this.state | float(0) > 0 %}
        mdi:solar-power
      {% else %}
        mdi:transmission-tower-import
      {% endif %}