substitutions:
  name: esp32-bluetooth-proxy-edc0c8
  friendly_name: Bluetooth Proxy edc0c8
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0F3CoFhixo0VqrV7GciaIZUmUn1G8PgUOlzBZO6Szxk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
