substitutions:
  name: esp8286-porte-garage
  friendly_name: Porte Garage
  description: Controle Porte Garage

packages:
  base: !include common/base.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${description}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name} AP
    password: !secret wifi_password

api:
  encryption:
    key: PVc+RKdJkSmTGm8FQ8vkjz0y2TxZKMn9afxm1AiM5r4=

# status de la led du signal wifi
status_led:
  pin: GPIO2

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    icon: mdi:switch
    pin: GPIO4
    id: relay

button:
  - platform: template
    name: "${friendly_name} Porte de garage"
    on_press:
      - switch.turn_on: relay
      - delay: 500ms
      - switch.turn_off: relay



#output:
#  - platform: gpio
#    id: relay
#    pin: GPIO4
#button:
#  - platform: output
#    name: "${friendly_name} Porte de garage"
#    icon: mdi:garage
#    output: relay
#    duration: 500ms

