substitutions:
  name: esphome-web-da0b84
  friendly_name: ESPHome Web da0b84
  impulsfactor_gas: "0.01"
  update_interval: 60s
  update_interval_sensor: 10s

packages:
  base: !include common/base.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

api:
  encryption:
    key: RXR3bYhhfGhAyJgIRypD1zIGWHCBrkS0HDAC6DPBBBK=
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter_gas
    pin: GPIO12 
    internal: true
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - lambda: id(total_pulses_gas) += 1;

globals:
  - id: total_pulses_gas
    type: int
    restore_value: false
    initial_value: '0'
    
sensor:
  - platform: template
    name: "Gas used"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    update_interval: ${update_interval}
    lambda: |-
        return id(total_pulses_gas) * ${impulsfactor_gas};