substitutions:
  name: esphome-web-da0b84
  friendly_name: ESPHome Web da0b84

packages:
  base: !include common/base.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${description}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name} AP
    password: !secret wifi_password

api:
  encryption:
    key: PVc+RKdJkSmTGm8FQ8vkjz0y2TxZKMn9afxm1AiM5r4=

