id: garage_door_open_notification
alias: "Garage Door - Open Notification"
description: "Send notification when garage door opens"
triggers:
  - trigger: state
    entity_id: sensor.garage_door_position
    to: "2.0"
conditions:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown'] }}"
actions:
  - action: notify.mobile_app_fred_16_pro
    data:
      message: "Porte de garage ouverte"
