id: garage_water_tank_empty_notification
alias: "Water Tank - Empty Notification"
description: "Send notification when water tank is below 500l"
triggers:
  - trigger: numeric_state
    entity_id: sensor.water_tank_level_litres
    below: 500
conditions:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unavailable', 'unknown'] }}"
actions:
  - action: notify.mobile_app_fred_16_pro
    data:
      message: "Citerne eau de pluie presque vide"
