substitutions:
  name: esp32-bluetooth-proxy-ee2b8c
  friendly_name: Bluetooth Proxy Salon (ee2b8c)

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
  bluethoot-proxy: !include common/base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: 0vVYJz0UISdnRYx4pt0VLnlY9GBRgPwoEJu5ztC80Ow=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
