substitutions:
  name: esphome-web-a0ffb4
  friendly_name: ESPHome Web a0ffb4
packages:
  base: !include common/base.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: 1cRmyqYqt7bXFkkq1ACvn5GeH1wjqZvDvpDn1sNuMi0=
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

remote_receiver:
  pin: GPIO13
  dump: all