substitutions:
  name: muino-water-meter-e5f25c
packages:
  esphome.muino-water-meter: github://martijnvwezel/watermeter-esphome/muino-water-meter-esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: R+AsYdoyOTjIUfsxa4gfk1BN6soMzkdmUJwWWJNwsl0=
web_server:
  port: 80
  
wifi:
  ssid: Midgard-Garage
  password: !secret wifi_password
